### ISSUE TITLE
cro installation gives warnings

### ISSUE THREAD

**Issue by jnthn** [croservices/cro#75] opened 2018-08-31 10:18 UTC
```
===> Installing: cro:ver<0.7.6>
Potential difficulties:
    Asked to remove 12 spaces, but the shortest indent is 0 spaces
    at /home/jnthn/dev/cro/cro/site#sources/D44F060F1508953EA54C88CF61E79D8A11D3BFDA (Cro::Tools::Template::ReactReduxSPA):144
    ------>             CODE⏏<EOL>
    Asked to remove 12 spaces, but the shortest indent is 1 spaces
    at /home/jnthn/dev/cro/cro/site#sources/D44F060F1508953EA54C88CF61E79D8A11D3BFDA (Cro::Tools::Template::ReactReduxSPA):144
    ------>             CODE⏏<EOL>

1 bin/ script [cro] installed to:
/home/jnthn/dev/MoarVM/install/share/perl6/site/bin
```

**Comment by Altai-man** [comment] 2018-09-07 10:29
Cannot reproduce it. On my local system and with docker fresh container:
```
root@d08ef48d8fcd:/# zef --force install cro
===> Searching for: cro
===> Searching for missing dependencies: IO::Socket::Async::SSL, YAMLish, Cro::WebSocket, Docker::File, File::Ignore
===> Searching for missing dependencies: Cro::HTTP, Base64, Digest::SHA1::Native, Crypt::Random, OpenSSL
===> Searching for missing dependencies: IO::Path::ChildSecure, HTTP::HPACK, Cro::Core, Cro::TLS, JSON::JWT, if
===> Searching for missing dependencies: Digest::HMAC
===> Searching for missing dependencies: Digest
===> Building: Digest::SHA1::Native:ver<0.03>
===> Building [OK] for Digest::SHA1::Native:ver<0.03>
===> Testing: OpenSSL:ver<0.1.21>:auth<github:sergot>
# NETWORK_TESTING was not set
Cannot locate symbol 'sk_num' in native library 'libssl.so'
  in method setup at /usr/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 283
  in method CALL-ME at /usr/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 570
  in block <unit> at t/10-client-ca-file.t line 10

# Looks like you planned 7 tests, but ran 1
# NETWORK_TESTING was not set
===> Testing [FAIL]: OpenSSL:ver<0.1.21>:auth<github:sergot>
Failed to get passing tests, but continuing with --force-test
===> Testing: IO::Socket::Async::SSL:ver<0.7.0>
===> Testing [OK] for IO::Socket::Async::SSL:ver<0.7.0>
===> Testing: YAMLish:ver<0.0.4>:auth<Leon Timmermans>
===> Testing [OK] for YAMLish:ver<0.0.4>:auth<Leon Timmermans>
===> Testing: IO::Path::ChildSecure:ver<1.001011>
===> Testing [OK] for IO::Path::ChildSecure:ver<1.001011>
===> Testing: Base64:ver<0.0.1>:auth<github:ugexe>
===> Testing [OK] for Base64:ver<0.0.1>:auth<github:ugexe>
===> Testing: HTTP::HPACK:ver<0.9.2>
===> Testing [OK] for HTTP::HPACK:ver<0.9.2>
===> Testing: Cro::Core:ver<0.7.6>
===> Testing [OK] for Cro::Core:ver<0.7.6>
===> Testing: Cro::TLS:ver<0.7.6>
===> Testing [OK] for Cro::TLS:ver<0.7.6>
===> Testing: if:ver<0.1.0>:auth<github:FROGGS>
===> Testing [OK] for if:ver<0.1.0>:auth<github:FROGGS>
===> Testing: Crypt::Random:ver<0.4.1>:auth<github:skinkade>
===> Testing [OK] for Crypt::Random:ver<0.4.1>:auth<github:skinkade>
===> Testing: Digest:ver<0.3.4>:auth<Lucien Grondin>
===> Testing [OK] for Digest:ver<0.3.4>:auth<Lucien Grondin>
===> Testing: Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
===> Testing [OK] for Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
===> Testing: JSON::JWT:ver<1.0>:auth<github:retupmoca>
===> Testing [OK] for JSON::JWT:ver<1.0>:auth<github:retupmoca>
===> Testing: Cro::HTTP:ver<0.7.6.1>
===> Testing [OK] for Cro::HTTP:ver<0.7.6.1>
===> Testing: Digest::SHA1::Native:ver<0.03>
===> Testing [OK] for Digest::SHA1::Native:ver<0.03>
===> Testing: Cro::WebSocket:ver<0.7.6>
===> Testing [OK] for Cro::WebSocket:ver<0.7.6>
===> Testing: Docker::File:ver<1.0>:auth<github:jnthn>
===> Testing [OK] for Docker::File:ver<1.0>:auth<github:jnthn>
===> Testing: File::Ignore
===> Testing [OK] for File::Ignore
===> Testing: cro:ver<0.7.6>
# Check service up attempt 1: connection refused
# Check service up attempt 2: connection refused
# Check service up attempt 3: connection refused
# Check service up attempt 4: connection refused
# Check service up attempt 5: connection refused
# Check service up attempt 6: connection refused
# Check service up attempt 7: connection refused
# Check service up attempt 8: connection refused
# Check service up attempt 9: connection refused
# Check service up attempt 10: connection refused
# Check service up attempt 11: connection refused
# Check service up attempt 12: connection refused
# Check service up attempt 13: connection refused
# Check service up attempt 14: connection refused
# Check service up attempt 15: connection refused
# Check service up attempt 16: connection refused
# Check service up attempt 17: connection refused
# Check service up attempt 18: connection refused
# Check service up attempt 19: connection refused
# Check service up attempt 20: connection refused
# Check service up attempt 21: connection refused
# Check service up attempt 22: connection refused
# Check service up attempt 23: connection refused
# Check service up attempt 24: connection refused
# Check service up attempt 25: connection refused
# Check service up attempt 26: connection refused
# Check service up attempt 27: connection refused
# Check service up attempt 28: connection refused
# Check service up attempt 29: connection refused
# Check service up attempt 30: connection refused
# Check service up attempt 31: connection refused
# Check service up attempt 32: connection refused
# Check service up attempt 33: connection refused
# Check service up attempt 34: connection refused
# Check service up attempt 35: connection refused
# Check service up attempt 36: connection refused
# Check service up attempt 37: connection refused
# Check service up attempt 38: connection refused
# Check service up attempt 39: connection refused
# Check service up attempt 40: connection refused
# Failed test 'Could call the started service'
# at t/tools-runner.t line 63
# Failed test 'Got expected resposne from service'
# at t/tools-runner.t line 64
# expected: 'Service 1 OK'
#      got: (Any)
# Failed test 'Was not on STDERR'
# at t/tools-runner.t line 68
# Failed test 'Got log line mentioning status code'
# at t/tools-runner.t line 69
# Check service up attempt 1: connection refused
# Check service up attempt 2: connection refused
# Check service up attempt 3: connection refused
# Check service up attempt 4: connection refused
# Check service up attempt 5: connection refused
# Check service up attempt 6: connection refused
# Check service up attempt 7: connection refused
# Check service up attempt 8: connection refused
# Check service up attempt 9: connection refused
# Check service up attempt 10: connection refused
# Check service up attempt 11: connection refused
# Check service up attempt 12: connection refused
# Check service up attempt 13: connection refused
# Check service up attempt 14: connection refused
# Check service up attempt 15: connection refused
# Check service up attempt 16: connection refused
# Check service up attempt 17: connection refused
# Check service up attempt 18: connection refused
# Check service up attempt 19: connection refused
# Check service up attempt 20: connection refused
# Check service up attempt 21: connection refused
# Check service up attempt 22: connection refused
# Check service up attempt 23: connection refused
# Check service up attempt 24: connection refused
# Check service up attempt 25: connection refused
# Check service up attempt 26: connection refused
# Check service up attempt 27: connection refused
# Check service up attempt 28: connection refused
# Check service up attempt 29: connection refused
# Check service up attempt 30: connection refused
# Check service up attempt 31: connection refused
# Check service up attempt 32: connection refused
# Check service up attempt 33: connection refused
# Check service up attempt 34: connection refused
# Check service up attempt 35: connection refused
# Check service up attempt 36: connection refused
# Check service up attempt 37: connection refused
# Check service up attempt 38: connection refused
# Check service up attempt 39: connection refused
# Check service up attempt 40: connection refused
# Failed test 'Could call the restarted service'
# at t/tools-runner.t line 80
# Failed test 'Got response indicating new service running'
# at t/tools-runner.t line 81
# expected: 'Service 1 UPDATED'
#      got: (Any)
# Failed test 'Was not on STDERR'
# at t/tools-runner.t line 85
# Failed test 'Got log line mentioning status code'
# at t/tools-runner.t line 86
# Looks like you failed 8 tests of 20
===> Testing [FAIL]: cro:ver<0.7.6>
Failed to get passing tests, but continuing with --force-test
===> Installing: OpenSSL:ver<0.1.21>:auth<github:sergot>
===> Installing: IO::Socket::Async::SSL:ver<0.7.0>
===> Installing: YAMLish:ver<0.0.4>:auth<Leon Timmermans>
===> Installing: IO::Path::ChildSecure:ver<1.001011>
===> Installing: Base64:ver<0.0.1>:auth<github:ugexe>
===> Installing: HTTP::HPACK:ver<0.9.2>
===> Installing: Cro::Core:ver<0.7.6>
===> Installing: Cro::TLS:ver<0.7.6>
===> Installing: if:ver<0.1.0>:auth<github:FROGGS>
===> Installing: Crypt::Random:ver<0.4.1>:auth<github:skinkade>
===> Installing: Digest:ver<0.3.4>:auth<Lucien Grondin>
===> Installing: Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
===> Installing: JSON::JWT:ver<1.0>:auth<github:retupmoca>
===> Installing: Cro::HTTP:ver<0.7.6.1>
===> Installing: Digest::SHA1::Native:ver<0.03>
===> Installing: Cro::WebSocket:ver<0.7.6>
===> Installing: Docker::File:ver<1.0>:auth<github:jnthn>
===> Installing: File::Ignore
===> Installing: cro:ver<0.7.6>

1 bin/ script [cro] installed to:
/usr/share/perl6/site/bin
root@d08ef48d8fcd:/# 
```

**Comment by Altai-man** [comment] 2018-10-07 17:08
Hopefully fixed with https://github.com/croservices/cro/commit/a0b51111e741ffd2a5ccddc550839111ebda4807

**Closed by Altai-man** 2018-10-07 17:08 UTC
